use std::fmt;

#[derive(Clone)]
pub enum UrlPath {
    Accounts,
    ApplicationFees,
    Authorizations,
    Balance,
    CardHolders,
    Charges,
    CheckoutSessions,
    CountrySpecs,
    Coupons,
    CreditNote,
    Customers,
    Disputes,
    Events,
    File(bool),
    FileLink,
    InvoiceItems,
    Invoices,
    IssuingDispute,
    IssuingCard,
    Order,
    PaymentIntents,
    PaymentMethods,
    Payouts,
    Plans,
    Products,
    Refunds,
    OrderReturns,
    RadarValueList,
    RadarValueListItems,
    Reviews,
    Sigma,
    Sku,
    Sources,
    Subscriptions,
    SubscriptionItems,
    SubscriptionSchedules,
    TerminalConnectionTokens,
    TerminalLocations,
    TerminalReaders,
    Tokens,
    Topups,
    Transactions,
    Transfers,
    WebhookEndpoints,
    Other(String),
}

impl fmt::Display for UrlPath {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let uri = match *self {
            UrlPath::Accounts => "/accounts",
            UrlPath::Authorizations => "/issuing/authorzations",
            UrlPath::ApplicationFees => "/application_fees",
            UrlPath::Balance => "/balance",
            UrlPath::CardHolders => "/issuing/cardholders",
            UrlPath::Charges => "/charges",
            UrlPath::CheckoutSessions => "/checkout/sessions",
            UrlPath::CountrySpecs => "/country_specs",
            UrlPath::Coupons => "/coupons",
            UrlPath::Customers => "/customers",
            UrlPath::CreditNote => "/credit_notes",
            UrlPath::Disputes => "/disputes",
            UrlPath::Events => "/events",
            UrlPath::File(_) => "/files",
            UrlPath::FileLink => "/file_link",
            UrlPath::IssuingCard => "/issuing/cards",
            UrlPath::IssuingDispute => "/issuing/disputes",
            UrlPath::InvoiceItems => "/invoiceitems",
            UrlPath::Invoices => "/invoices",
            UrlPath::Order => "/order",
            UrlPath::PaymentMethods => "/payment_methods",
            UrlPath::PaymentIntents => "/payment_intents",
            UrlPath::Payouts => "/payouts",
            UrlPath::Plans => "/plans",
            UrlPath::Products => "/products",
            UrlPath::RadarValueList => "/radar/value_lists",
            UrlPath::RadarValueListItems => "/radar/value_list_items",
            UrlPath::Reviews => "/reviews",
            UrlPath::Refunds => "/refunds",
            UrlPath::OrderReturns => "/order_returns",
            UrlPath::Sigma => "/sigma/scheduled_query_runs",
            UrlPath::Sku => "/skus",
            UrlPath::Sources => "/sources",
            UrlPath::Subscriptions => "/subscriptions",
            UrlPath::SubscriptionItems => "/subscription_items",
            UrlPath::SubscriptionSchedules => "/subscription_schedules",
            UrlPath::TerminalConnectionTokens => "/terminal/connection_tokens",
            UrlPath::TerminalLocations => "/terminal/locations",
            UrlPath::TerminalReaders => "/terminal/readers",
            UrlPath::Tokens => "/tokens",
            UrlPath::Topups => "/topups",
            UrlPath::Transactions => "/issuing/transactions",
            UrlPath::Transfers => "/transfers",
            UrlPath::WebhookEndpoints => "/webhook_endpoints",
            UrlPath::Other(ref path) => &path,
        };
        write!(f, "{}", uri)
    }
}